class DataService {
  async getData() {
    const response = await fetch('data.json', { cache: 'no-store' });
    if (!response.ok) throw new Error('Could not load data.json');
    return response.json();
  }
}
class ThemeManager {
  constructor(){ this.key='hds-theme'; this.root=document.documentElement; }
  init(){ this.set(localStorage.getItem(this.key)||'light'); }
  set(theme){ this.root.dataset.theme=theme; localStorage.setItem(this.key,theme); document.querySelectorAll('[data-theme-icon]').forEach(el=>el.textContent=theme==='dark'?'☀️':'🌙'); }
  toggle(){ this.set(this.root.dataset.theme==='dark'?'light':'dark'); }
}
class WhatsAppService { constructor(number){ this.number=number; } open(message){ window.open(`https://wa.me/${this.number}?text=${encodeURIComponent(message)}`,'_blank','noopener'); } }
class Component { constructor(data){ this.data=data; } html(){ return ''; } }
class Header extends Component {
  html(){
    const { business, clientWebDesign } = this.data;
    const clientLinks = clientWebDesign.projects.map(project => `<a href="${project.liveUrl || project.localPage || `client-web-design.html?id=${project.id}`}">${project.name}</a>`).join('');
    return `<header class="header"><div class="container nav">
      <a href="#home" class="logo" aria-label="${business.name} home"><span class="logo-mark"><img class="logo-image" src="assets/cartoon-transparent.png" alt="" /></span><span><strong>${business.name}</strong><small>${business.tagline}</small></span></a>
      <nav class="nav-links" data-nav-links>
        <a class="active" href="#home">Home</a>
        <div class="nav-dropdown"><button type="button" class="dropdown-trigger" aria-haspopup="true" aria-expanded="false">Services ▾</button><div class="dropdown-menu"><a href="#services">Service Categories</a><a href="shop.html">Packages</a><a href="#growth-engine">Growth Engine</a></div></div>
        <a href="#services">Solutions</a>
        <div class="nav-dropdown"><button type="button" class="dropdown-trigger" aria-haspopup="true" aria-expanded="false">Client Work ▾</button><div class="dropdown-menu">${clientLinks}</div></div>
        <a href="shop.html">Shop</a><a href="#about">About</a><div class="nav-dropdown"><button type="button" class="dropdown-trigger" aria-haspopup="true" aria-expanded="false">Contact ▾</button><div class="dropdown-menu"><a href="#contact">Contact</a><a href="careers.html">Careers</a></div></div>
      <div class="mobile-menu-tools"><span class="mobile-menu-tools-title">Display</span><button class="mobile-theme-row" type="button" data-theme-toggle aria-label="Toggle theme"><span class="theme-switch-control"><span class="theme-switch-thumb" data-theme-icon>🌙</span></span><strong>Theme</strong></button></div></nav>
      <div class="nav-actions"><button class="theme-switch" type="button" data-theme-toggle aria-label="Toggle theme"><span class="theme-switch-control"><span class="theme-switch-thumb" data-theme-icon>🌙</span></span></button><a class="btn btn-primary btn-small" href="#booking">Book a Call</a><button class="menu-toggle" data-menu-toggle aria-label="Open menu">☰</button></div>
    </div></header>`;
  }
}
class Hero extends Component {
  html(){
    const trustedIcons = { web:'<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="10" y="14" width="44" height="30" rx="4" fill="currentColor" opacity=".26"/><rect x="14" y="18" width="36" height="22" rx="2" fill="currentColor"/><path d="M22 49h20l4 5H18l4-5Z" fill="currentColor" opacity=".72"/></svg>', whatsapp:'<svg viewBox="0 0 64 64" aria-hidden="true"><path fill="currentColor" d="M32 8a23.5 23.5 0 0 0-20 35.8L8.6 56 21 52.7A23.5 23.5 0 1 0 32 8Zm0 5a18.5 18.5 0 0 1 15.7 28.3A18.5 18.5 0 0 1 23 47.7l-.8-.45-6.7 1.8 1.8-6.5-.5-.85A18.5 18.5 0 0 1 32 13Zm-7.2 9.4c-.45 0-1.15.16-1.75.82-.6.66-2.3 2.25-2.3 5.48 0 3.22 2.35 6.34 2.68 6.78.33.44 4.52 7.22 11.18 9.82 5.52 2.18 6.66 1.75 7.87 1.64 1.2-.1 3.9-1.6 4.45-3.13.55-1.54.55-2.85.39-3.13-.17-.27-.6-.43-1.26-.76-.66-.33-3.9-1.92-4.5-2.14-.6-.22-1.04-.33-1.48.33-.44.66-1.7 2.14-2.08 2.58-.38.44-.77.5-1.43.17-.66-.33-2.78-1.02-5.3-3.26-1.95-1.74-3.28-3.91-3.66-4.57-.38-.66-.04-1.02.29-1.35.3-.3.66-.77.98-1.15.33-.38.44-.66.66-1.1.22-.44.1-.82-.06-1.15-.16-.33-1.47-3.53-2.02-4.84-.53-1.27-1.08-1.1-1.48-1.12h-1.25Z"/></svg>', ai:'<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="15" y="21" width="34" height="28" rx="10" fill="currentColor" opacity=".84"/><path d="M32 15v6" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><circle cx="32" cy="12" r="4" fill="currentColor"/><circle cx="25" cy="34" r="4" fill="#fff"/><circle cx="39" cy="34" r="4" fill="#fff"/><path d="M25 43h14" stroke="#fff" stroke-width="4" stroke-linecap="round"/><path d="M12 32h5M47 32h5" stroke="currentColor" stroke-width="5" stroke-linecap="round"/></svg>', chart:'<svg viewBox="0 0 64 64" aria-hidden="true"><rect x="14" y="35" width="9" height="17" rx="3" fill="#3bd671"/><rect x="28" y="25" width="9" height="27" rx="3" fill="#ffb020"/><rect x="42" y="14" width="9" height="38" rx="3" fill="#8a4dff"/></svg>', cloud:'<svg viewBox="0 0 64 64" aria-hidden="true"><path d="M23 46h24a11 11 0 0 0 1-22 17 17 0 0 0-32-3 13 13 0 0 0 7 25Z" fill="currentColor" opacity=".9"/><path d="M23 46h24a11 11 0 0 0 1-22 17 17 0 0 0-32-3 13 13 0 0 0 7 25Z" fill="none" stroke="#fff" stroke-width="3" opacity=".65"/></svg>' };
    const trusted = [[trustedIcons.web,'Website Development','Modern, responsive and SEO-friendly websites that convert visitors into customers.','pink'],[trustedIcons.whatsapp,'WhatsApp Automation','Automate chats, capture leads and nurture customers 24/7 with smart WhatsApp flows.','green'],[trustedIcons.ai,'AI Sales Assistant','AI-powered assistants that engage, qualify leads and help close more deals automatically.','purple'],[trustedIcons.chart,'Dashboard & Analytics','Real-time dashboards and reports that turn data into actionable business insights.','orange'],[trustedIcons.cloud,'Cloud Solutions','Secure, scalable and reliable cloud solutions to support your business growth.','blue']].map(i=>`<article class="trusted-card trusted-card-${i[3]}"><span class="trusted-card-icon trusted-svg-icon">${i[0]}</span><div><h3>${i[1]}</h3><p>${i[2]}</p></div><a href="#services" aria-label="Explore ${i[1]}">→</a></article>`).join('');
    const trustProof = [['🛡','Trusted & Experienced','Serving businesses across Malaysia','pink'],['👥','Result Driven','Focused on measurable growth','purple'],['✅','Reliable Support',"We're here when you need us",'green'],['🔒','Secure & Compliant','Your data is safe with us','orange']].map(i=>`<article class="trusted-proof-item trusted-proof-${i[3]}"><span>${i[0]}</span><div><strong>${i[1]}</strong><small>${i[2]}</small></div></article>`).join('');
    const metrics = this.data.heroMetrics.map(m=>`<article class="float-card ${m.position}"><small>${m.label}</small><strong>${m.value}</strong><span class="trend">${m.trend}</span></article>`).join('');
    return `<section class="hero restored-hero" id="home"><div class="container hero-grid restored-hero-grid"><div class="hero-copy"><span class="badge hero-offer-badge">AI-Powered Marketing Solutions</span><h1>Build Your Website,<br><span class="gradient-text">Automate AI-Powered<br>Marketing Workflow<br>Increase Revenue,<br>Profit & Income</span></h1><p>We help SMEs grow with smart websites, WhatsApp automation, AI agents & business dashboards.</p><div class="hero-ctas"><a class="btn btn-primary" href="#services">View List of Services</a><a class="btn btn-whatsapp" href="#booking"><span aria-hidden="true">📅</span> Book A FREE Strategy Call</a></div><div class="stats restored-stats"><div class="stat-card"><strong>20+</strong><small>Years Experience</small></div><div class="stat-card"><strong>50+</strong><small>Projects Delivered</small></div><div class="stat-card"><strong>99%</strong><small>Support Response</small></div><div class="stat-card"><strong>5.0</strong><small>Client Rating<br>★★★★★</small></div></div></div><div class="hero-visual restored-visual"><div class="orbit"></div><img class="hero-avatar" src="assets/cartoon-transparent.png" alt="HDS Consultancy AI marketing avatar" />${metrics}</div></div><div class="container trusted-showcase"><div class="trusted-showcase-head"><span class="eyebrow">🛡 TRUSTED & RELIED UPON</span><h2>Trusted By Businesses<br><span class="gradient-text">Across Malaysia</span></h2><p>We deliver end-to-end digital solutions that help businesses attract more customers, automate operations and grow faster.</p></div><div class="trusted-card-grid">${trusted}<article class="trusted-card trusted-custom-card"><span class="trusted-custom-icon">💬</span><div><h3>Need a Custom Solution?</h3><p>Let's discuss how we can help your business grow.</p><a class="trusted-whatsapp" target="_blank" rel="noopener" href="https://wa.me/${this.data.business.whatsapp}">🟢 Chat With Us on WhatsApp <b>→</b></a></div></article></div><div class="trusted-proof-panel"><div class="trusted-proof-head"><span>WHY BUSINESSES CHOOSE US</span><h3>Trusted. Reliable. Results Driven.</h3></div><div class="trusted-proof-strip">${trustProof}</div></div></div></section>`;
  }
}
class Services extends Component {
  icon(tone, icon){ return `<span class="service-icon-badge service-icon-${tone}" aria-hidden="true">${icon}</span>`; }
  quick(tone, icon, title, text){ return `<article class="service-quick-card">${this.icon(tone, icon)}<div><strong>${title}</strong><small>${text}</small></div></article>`; }
  category(id,tone,icon,title,text,image){ return `<article class="service-category-card" id="${id}"><figure class="service-category-media"><img src="${image}" alt="${title}" loading="lazy" referrerpolicy="no-referrer" /></figure><div class="service-category-body"><h3>${title}</h3><p>${text}</p><a href="shop.html">Explore →</a></div></article>`; }
  step(title,text,tone,icon,num){ return `<article class="growth-step engine-step-${tone}"><span class="step-num">${num}</span><span class="engine-icon">${icon}</span><strong>${title}</strong><small>${text}</small></article>`; }
  html(){
    const quick = [this.quick('social','📣','Social Media Marketing','TikTok, Meta & Content'),this.quick('whatsapp','☎','WhatsApp Marketing','Broadcast & Automate'),this.quick('web','▣','Website Design','Build & Redesign'),this.quick('ai','✦','AI Automation','Smart Workflows'),this.quick('dashboard','▥','Sales Dashboard','Track & Grow Sales')].join('');
    const categories = [
      ['service-web-app-development','web','⌨','Web & App Development','Websites, web apps, mobile apps and custom solutions.','https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=900&q=80'],['service-marketing-growth','social','↗','Marketing & Growth','Social media, ads, content and SEO to grow your brand.','https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=900&q=80'],['service-automation-ai','ai','AI','Automation & AI','WhatsApp automation, AI chatbots and workflow automation.','https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=900&q=80'],['service-data-analytics','dashboard','▥','Data & Analytics','Dashboards, reporting and analytics for business insights.','https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80'],['service-cloud-devops','cloud','☁','Cloud & DevOps','Cloud setup, migration and integration on AWS, Azure & GCP.','https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=900&q=80'],['service-testing-quality','quality','◆','Testing & Quality','QA testing, performance and quality assurance solutions.','https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80'],['service-design-branding','design','✒','Design & Branding','Brand identity, UI/UX design and creative services.','https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=900&q=80'],['service-training-consulting','training','◈','Training & Consulting','Training, workshops and digital transformation consulting.','https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=900&q=80']
    ].map(c=>this.category(...c)).join('');
    const steps = [['Social Media Ads','Attract the right audience and increase engagement.','pink','📣','01'],['Website / Landing Page','Capture leads with high-converting pages and forms.','purple','▣','02'],['WhatsApp Automation','Nurture leads, automate replies and qualify customers.','green','☎','03'],['Sales Dashboard','Track performance, monitor results and make smarter decisions.','blue','▥','04'],['Repeat Customers','Create follow-ups and retain customers for loyal sales.','orange','♟','05'],['AI-Powered Solutions','Smarter automation for better results.','rose','✽','06'],['Secure & Reliable','Your data and systems are safe with us.','violet','◆','07'],['Custom & Scalable','Solutions built for your business growth.','emerald','✚','08']].map(s=>this.step(...s)).join('');
    return `<section class="section services-showcase" id="services"><div class="container"><div class="service-help-panel"><h2>We Help You Attract, Engage, Automate & Grow</h2><p>From social media to sales dashboard — we turn visitors into loyal customers.</p><div class="service-quick-grid">${quick}</div></div><div class="service-category-head services-enterprise-head"><span class="eyebrow">WHAT WE DO</span><h2>End-to-End <span class="gradient-text">Enterprise Business</span> Solutions</h2><p>Everything your business needs to launch, automate, market, test, integrate and scale in the digital age.</p><a class="btn btn-ghost btn-small" href="#service-categories">View List Categories</a></div><div class="service-category-grid" id="service-categories">${categories}</div><div class="growth-engine process-engine" id="growth-engine"><div class="growth-engine-head"><span class="eyebrow">OUR PROVEN PROCESS</span><h2>The Complete <span class="gradient-text">Growth Engine</span><br>For Your Business</h2><p>We connect the dots from marketing to automation and turn data into growth.</p></div><div class="growth-steps">${steps}</div><div class="growth-engine-cta"><span class="service-avatar-icon"><img src="assets/cartoon-transparent.png" alt="" /></span><div><strong>Ready to Grow Your Business?</strong><small>Let’s build your digital success story together.</small></div><a class="btn btn-primary btn-small" href="#booking">Book a Free Consultation</a><a class="btn btn-ghost btn-small" target="_blank" rel="noopener" href="https://wa.me/${this.data.business.whatsapp}">WhatsApp Us</a></div></div></div></section>`;
  }
}
class WhyUs extends Component { html(){ return `<section class="section" id="about"><div class="container split-card restored-about"><div class="about-image-wrap"><img class="about-avatar" src="assets/cartoon-transparent.png" alt="HDS Consultancy avatar" /></div><div><span class="badge">WHY CHOOSE HDS CONSULTANCY</span><h2>Smart Solutions. <span class="gradient-text">Real Results.</span></h2><p class="muted-copy">We are more than a normal agency. HDS Consultancy blends AI, marketing, web design, automation, cloud and practical delivery experience to help business owners move faster without overcomplicating technology.</p><div class="feature-list"><div class="feature-chip"><strong>AI-Powered</strong><small>Smarter automation for better results</small></div><div class="feature-chip"><strong>Data-Driven</strong><small>Insights that guide growth decisions</small></div><div class="feature-chip"><strong>Transparent</strong><small>Clear communication and practical delivery</small></div><div class="feature-chip"><strong>Results-Focused</strong><small>Designed around ROI and business outcomes</small></div></div><a class="btn btn-primary" href="#contact">Learn More About Us →</a></div></div></section>`; } }
class Portfolio extends Component { html(){ const cases=this.data.caseStudies.map(c=>`<article class="case-card"><h3>${c.title}</h3><strong>${c.metric}</strong><p>${c.label}<br>${c.period}</p><div class="spark"></div></article>`).join(''); return `<section class="section" id="portfolio"><div class="container"><div class="section-title"><span class="eyebrow">IMPACT VAULT</span><h2>Proof, Wins & <span class="gradient-text">Growth Signals</span></h2><p>A sharper place for business results, campaign wins and measurable growth stories.</p></div><div class="case-grid">${cases}</div></div></section>`; } }
class Careers extends Component { html(){ const roles=this.data.careers.roles.map(r=>`<option value="${r}">${r}</option>`).join(''); const benefits=this.data.careers.benefits.map(b=>`<span>${b}</span>`).join(''); return `<section class="section" id="careers"><div class="container career-panel"><div class="career-intro"><span class="badge">CAREERS</span><h2>Join Our<br>Team</h2><p>${this.data.careers.intro}</p><img class="career-avatar" src="assets/cartoon-transparent.png" alt="Join HDS Consultancy team" /><div class="benefit-row">${benefits}</div></div><form class="form-card" data-career-form><h3>Send Career Request</h3><p class="form-note">This opens WhatsApp with your application details ready to send.</p><label>Full Name<input required name="name" type="text" placeholder="e.g. Hema Shalini"></label><label>Role Interested In<select required name="role"><option value="">Select a role</option>${roles}</select></label><div class="two-fields"><label>Phone<input required name="phone" type="tel" placeholder="e.g. +60 12 345 6789"></label><label>Email<input required name="email" type="email" placeholder="e.g. hello@company.com"></label></div><label>Portfolio / LinkedIn<input name="portfolio" type="url" placeholder="https://..."></label><label>Short Message<textarea required name="message" rows="3" placeholder="Tell us about your skills and availability"></textarea></label><label>Resume / CV <span class="limit">max 5MB</span><input name="attachment" type="file" accept=".pdf,.doc,.docx,.png,.jpg,.jpeg"></label><button class="btn btn-primary" type="submit">Send to WhatsApp →</button></form></div></section>`; } }
class ContactBooking extends Component { html(){ const b=this.data.business, serviceOptions=this.data.services.map(s=>`<option value="${s.title}">${s.title}</option>`).join(''); return `<section class="section" id="contact"><div class="container contact-grid"><div class="info-card"><span class="badge">OUR LOCATION</span><h2>Visit Us in Rawang</h2><p><strong>${b.name}</strong><br>${b.location}</p><p>📞 <a href="tel:${b.phonePlain}">${b.phone}</a><br>✉️ <a href="mailto:${b.email}">${b.email}</a></p><a class="btn btn-primary" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(b.mapQuery)}">Get Directions</a><div class="contact-map-embed"><iframe class="map-frame" title="HDS Consultancy location map" src="${b.mapEmbed}" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></div></div><div class="booking-card" id="booking"><span class="badge">BOOK A CALL</span><h2>Let's Build Something Amazing Together</h2><p class="muted-copy small-copy">Schedule a consultation and let’s discuss how HDS Consultancy can help your business grow.</p><form data-booking-form><div class="two-fields"><label>Name<input required name="name" type="text" placeholder="e.g. Hema Shalini"></label><label>Phone<input required name="phone" type="tel" placeholder="e.g. +60 12 345 6789"></label></div><label>Email<input required name="email" type="email" placeholder="e.g. hello@company.com"></label><label>Service<select required name="service"><option value="">Choose a service to discuss</option>${serviceOptions}</select></label><label>Query / Details<textarea required name="message" rows="3" placeholder="Tell us your goal, timeline, budget range, or the problem you want to solve"></textarea></label><button class="btn btn-primary" type="submit">Submit to WhatsApp →</button></form></div></div></section>`; } }
class Footer extends Component { html(){ const b=this.data.business; const icon='<svg viewBox="0 0 32 32" aria-hidden="true" focusable="false"><path fill="currentColor" d="M16.03 4.5A11.42 11.42 0 0 0 6.2 21.72L4.9 27.5l5.9-1.24A11.5 11.5 0 1 0 16.03 4.5Zm0 20.7c-1.83 0-3.6-.53-5.12-1.54l-.37-.24-3.08.65.68-3.01-.25-.39a9.16 9.16 0 1 1 8.14 4.53Zm5.03-6.84c-.27-.14-1.62-.8-1.87-.89-.25-.09-.43-.14-.61.14-.18.27-.7.89-.86 1.07-.16.18-.32.2-.59.07-.27-.14-1.15-.42-2.19-1.35-.81-.72-1.36-1.62-1.52-1.89-.16-.27-.02-.42.12-.55.13-.13.27-.32.41-.48.14-.16.18-.27.27-.45.09-.18.05-.34-.02-.48-.07-.14-.61-1.47-.84-2.01-.22-.53-.45-.46-.61-.47h-.52c-.18 0-.48.07-.73.34-.25.27-.95.93-.95 2.28 0 1.34.98 2.64 1.11 2.82.14.18 1.93 2.94 4.67 4.12.65.28 1.16.45 1.56.58.66.21 1.25.18 1.72.11.52-.08 1.62-.66 1.85-1.3.23-.64.23-1.19.16-1.3-.07-.12-.25-.19-.52-.33Z"/></svg>'; return `<footer class="footer"><div class="container footer-grid"><div><a href="#home" class="logo"><span class="logo-mark"><img class="logo-image" src="assets/cartoon-transparent.png" alt="" /></span><span><strong>${b.name}</strong><small>${b.tagline}</small></span></a><p>AI-powered digital marketing and tech consultancy for websites, automation, cloud, training and business growth.</p></div><div><h4>Services</h4><a href="#services">All Services</a><a href="shop.html">Shop Packages</a></div><div><h4>Company</h4><a href="#about">About Us</a><a href="#portfolio">Impact Vault</a><a href="careers.html">Careers</a></div><div><h4>Contact</h4><a href="tel:${b.phonePlain}">${b.phone}</a><a href="mailto:${b.email}">${b.email}</a><a href="https://wa.me/${b.whatsapp}" target="_blank" rel="noopener">WhatsApp Us</a></div></div></footer><a class="whatsapp-float" target="_blank" rel="noopener" aria-label="Chat with HDS Consultancy on WhatsApp" href="https://wa.me/${b.whatsapp}?text=${encodeURIComponent('Hi HDS Consultancy, I would like to enquire about your services.')}">${icon}</a>`; } }
class App {
  constructor(rootId){ this.root=document.getElementById(rootId); this.theme=new ThemeManager(); this.dataService=new DataService(); this.maxFileSizeMB=5; }
  async init(){ try{ this.data=await this.dataService.getData(); this.whatsapp=new WhatsAppService(this.data.business.whatsapp); this.maxFileSizeMB=this.data.booking?.attachmentLimitMB||5; this.render(); this.theme.init(); this.bindEvents(); } catch(error){ this.root.innerHTML=`<main class="container"><h1>Unable to load website</h1><p>${error.message}</p></main>`; } }
  render(){ this.root.innerHTML=[new Header(this.data),new Hero(this.data),new Services(this.data),new WhyUs(this.data),new Portfolio(this.data),new ContactBooking(this.data),new Footer(this.data)].map(c=>c.html()).join(''); }
  bindEvents(){ document.querySelectorAll('[data-theme-toggle]').forEach(btn=>btn.addEventListener('click',()=>this.theme.toggle()));
const navLinks = document.querySelector('[data-nav-links]');
const menuToggle = document.querySelector('[data-menu-toggle]');
const setMenuState = open => {
  navLinks?.classList.toggle('open', open);
  if (menuToggle) {
    menuToggle.textContent = open ? '×' : '☰';
    menuToggle.setAttribute('aria-expanded', String(open));
    menuToggle.setAttribute('aria-label', open ? 'Close menu' : 'Open menu');
  }
  document.body.classList.toggle('menu-open', open);
  if (!open) document.querySelectorAll('.nav-dropdown.open').forEach(d => { d.classList.remove('open'); d.querySelector('.dropdown-trigger')?.setAttribute('aria-expanded','false'); });
};
menuToggle?.setAttribute('aria-expanded', 'false');
menuToggle?.addEventListener('click', e => { e.stopPropagation(); setMenuState(!navLinks?.classList.contains('open')); });
const closeMobileMenu = () => setMenuState(false);
document.querySelectorAll('.nav-links a').forEach(a => a.addEventListener('click', closeMobileMenu));
document.addEventListener('click', e => { if (navLinks?.classList.contains('open') && !e.target.closest('[data-nav-links]') && !e.target.closest('[data-menu-toggle]')) setMenuState(false); });
document.addEventListener('keydown', e => { if (e.key === 'Escape') setMenuState(false); }); this.bindDropdowns(); document.querySelector('[data-booking-form]')?.addEventListener('submit',e=>this.handleBooking(e)); document.querySelector('[data-career-form]')?.addEventListener('submit',e=>this.handleCareer(e)); }
  bindDropdowns(){ const close=()=>document.querySelectorAll('.nav-dropdown.open').forEach(d=>{d.classList.remove('open');d.querySelector('.dropdown-trigger')?.setAttribute('aria-expanded','false');}); document.querySelectorAll('.nav-dropdown').forEach(d=>d.querySelector('.dropdown-trigger')?.addEventListener('click',e=>{e.stopPropagation();const open=!d.classList.contains('open');close();d.classList.toggle('open',open);d.querySelector('.dropdown-trigger')?.setAttribute('aria-expanded',String(open));})); document.addEventListener('click',e=>{if(!e.target.closest('.nav-dropdown')) close();}); }
  handleBooking(event){ event.preventDefault(); const data=Object.fromEntries(new FormData(event.currentTarget).entries()); this.whatsapp.open(`Hi HDS Consultancy, I would like to book a strategy call.\n\nName: ${data.name}\nPhone: ${data.phone}\nEmail: ${data.email}\nService: ${data.service}\nQuery: ${data.message}`); }
  handleCareer(event){ event.preventDefault(); const data=Object.fromEntries(new FormData(event.currentTarget).entries()); this.whatsapp.open(`Hi HDS Consultancy, I would like to apply / send a career request.\n\nName: ${data.name}\nRole: ${data.role}\nPhone: ${data.phone}\nEmail: ${data.email}\nPortfolio/LinkedIn: ${data.portfolio || '-'}\nMessage: ${data.message}`); }
}
new App('app').init();
