class DataService { async getData(){ const response=await fetch('data.json',{cache:'no-store'}); if(!response.ok) throw new Error('Could not load data.json'); return response.json(); } }
class ThemeManager { constructor(){ this.key='hds-theme'; this.root=document.documentElement; } init(){ this.set(localStorage.getItem(this.key)||'light'); } set(theme){ this.root.dataset.theme=theme; localStorage.setItem(this.key,theme); document.querySelectorAll('[data-theme-icon]').forEach(el=>el.textContent=theme==='dark'?'☀️':'🌙'); } toggle(){ this.set(this.root.dataset.theme==='dark'?'light':'dark'); } }
class CartPage {
  constructor(rootId){ this.root=document.getElementById(rootId); this.dataService=new DataService(); this.theme=new ThemeManager(); this.storageKey='hds-shop-cart'; this.currencyKey='hds-shop-currency'; this.currency='MYR'; this.cart=[]; }
  async init(){ try{ this.data=await this.dataService.getData(); this.currency=localStorage.getItem(this.currencyKey)||this.data.shop.defaultCurrency||'MYR'; this.cart=this.loadCart().filter(item=>this.getProduct(item.id)); this.saveCart(); this.render(); this.theme.init(); this.bindEvents(); this.renderCart(); } catch(error){ this.root.innerHTML=`<main class="container"><h1>Unable to load cart</h1><p>${error.message}</p></main>`; } }
  headerHtml(){ const b=this.data.business; const currencySymbols={MYR:'RM',USD:'$',SGD:'S$',AUD:'A$',EUR:'€',GBP:'£'}; const opts=this.data.shop.currencies.map(c=>`<option value="${c}" ${c===this.currency?'selected':''}>${currencySymbols[c]||c}</option>`).join(''); return `<header class="header"><div class="container nav"><a href="index.html#home" class="logo"><span class="logo-mark"><img class="logo-image" src="assets/cartoon-transparent.png" alt="" /></span><span><strong>${b.name}</strong><small>${b.tagline}</small></span></a><div class="nav-actions"><a class="btn btn-ghost btn-small" href="shop.html">Add Packages</a><label class="nav-currency-control"><span class="sr-only">Currency</span><select data-currency-select>${opts}</select></label><button class="theme-switch" type="button" data-theme-toggle aria-label="Toggle theme"><span class="theme-switch-control"><span class="theme-switch-thumb" data-theme-icon>🌙</span></span></button></div></div></header>`; }
  mainHtml(){ return `<main class="cart-page-main"><section class="cart-page-hero"><div class="container shop-heading"><div><span class="eyebrow">SELECTED PACKAGES</span><h1>Add or <span class="gradient-text">Edit</span> Your Package</h1><p>Review selected services, adjust quantity or add more packages.</p></div></div></section><section class="section"><div class="container cart-review-layout"><div class="cart-review-panel"><div class="cart-items" data-cart-items></div></div><aside class="cart-summary-card"><span class="eyebrow">SUMMARY</span><div class="cart-total-row"><span>Total</span><strong data-cart-total></strong></div><a class="btn btn-ghost" href="shop.html">Add More Packages</a><button class="btn btn-primary cart-checkout" type="button" data-cart-checkout>Confirm via WhatsApp</button><p class="form-note">Scope, timeline and payment details can still be confirmed before work starts.</p></aside></div></section></main>`; }
  render(){ this.root.innerHTML=`${this.headerHtml()}${this.mainHtml()}`; }
  bindEvents(){ document.querySelectorAll('[data-theme-toggle]').forEach(btn=>btn.addEventListener('click',()=>this.theme.toggle())); document.querySelector('[data-currency-select]')?.addEventListener('change',e=>{ this.currency=e.target.value; localStorage.setItem(this.currencyKey,this.currency); this.renderCart(); }); document.querySelector('[data-cart-items]')?.addEventListener('click',e=>this.handleCartAction(e)); document.querySelector('[data-cart-checkout]')?.addEventListener('click',()=>this.checkout()); }
  products(){ return this.data.shop.products||[]; } getProduct(id){ return this.products().find(p=>p.id===id); }
  exchangeRate(){ return this.data.shop.exchangeRates?.[this.currency]||1; } convertMYR(amount){ return Math.round(amount*this.exchangeRate()); } formatMoney(amount){ return new Intl.NumberFormat('en-US',{style:'currency',currency:this.currency,maximumFractionDigits:0}).format(amount); } formatMYR(amount){ return this.formatMoney(this.convertMYR(amount)); }
  isCustom(product){ return product.priceType==='custom'||Number(product.price||0)>=5000; }
  productAmount(product){ if(this.isCustom(product)) return 0; const p=product.price||{}; if(typeof p==='number') return this.convertMYR(p); if(p.type==='quote') return 0; return this.convertMYR(p.amount||p.setup||p.min||0); }
  priceText(product){ if(this.isCustom(product)) return 'Custom Pricing'; if(typeof product.price==='number'){ const amount=this.formatMYR(product.price); if(product.priceType==='monthly') return `${amount}/month`; return `${product.pricePrefix?`${product.pricePrefix} `:''}${amount}${product.priceNote?` ${product.priceNote}`:''}`; } const p=product.price||{}; if(p.type==='quote') return 'Quotation required'; if(p.type==='from') return `From ${this.formatMYR(p.amount)}`; if(p.type==='range'||p.type==='rangePlus') return `${this.formatMYR(p.min)} - ${this.formatMYR(p.max)}${p.type==='rangePlus'?'+':''}`; if(p.type==='setupMonthly') return `${this.formatMYR(p.setup)} setup + ${this.formatMYR(p.monthly)}/month`; if(p.type==='monthly') return `${this.formatMYR(p.amount)}/month`; return this.formatMoney(this.productAmount(product)); }
  loadCart(){ try{return JSON.parse(localStorage.getItem(this.storageKey)||'[]');}catch{return [];} } saveCart(){ localStorage.setItem(this.storageKey,JSON.stringify(this.cart)); }
  handleCartAction(e){ const b=e.target.closest('[data-cart-action]'); if(!b) return; const item=this.cart.find(i=>i.id===b.dataset.productId); if(!item) return; if(b.dataset.cartAction==='increase') item.quantity++; if(b.dataset.cartAction==='decrease') item.quantity--; if(b.dataset.cartAction==='remove'||item.quantity<=0) this.cart=this.cart.filter(i=>i.id!==b.dataset.productId); this.saveCart(); this.renderCart(); }
  renderCart(){ const wrap=document.querySelector('[data-cart-items]'), totalEl=document.querySelector('[data-cart-total]'), checkout=document.querySelector('[data-cart-checkout]'); if(!wrap||!totalEl) return; const total=this.cart.reduce((sum,item)=>{ const p=this.getProduct(item.id); return sum+(p?this.productAmount(p)*item.quantity:0); },0); totalEl.textContent=this.formatMoney(total); if(checkout) checkout.disabled=this.cart.length===0; if(!this.cart.length){ wrap.innerHTML=`<div class="empty-cart-card"><h2>No package selected yet</h2><p>Go back to the shop and choose a package.</p><a class="btn btn-primary" href="shop.html">Add Package</a></div>`; return; } wrap.innerHTML=this.cart.map(item=>{ const p=this.getProduct(item.id); if(!p) return ''; const line=this.productAmount(p)*item.quantity; const note=p.priceNote||p.price?.cadence||p.duration||''; return `<article class="cart-item"><div><span class="category">${p.group}</span><strong>${p.title}</strong><small>${this.priceText(p)}${note?` • ${note}`:''}</small></div><div class="cart-qty"><button data-cart-action="decrease" data-product-id="${p.id}">-</button><span>${item.quantity}</span><button data-cart-action="increase" data-product-id="${p.id}">+</button></div><strong>${line?this.formatMoney(line):'Quote'}</strong><button class="cart-remove" data-cart-action="remove" data-product-id="${p.id}">Remove</button></article>`; }).join(''); }
  checkout(){ if(!this.cart.length) return; const lines=this.cart.map(item=>{ const p=this.getProduct(item.id); const line=this.productAmount(p)*item.quantity; return `${p.title} x ${item.quantity} - ${line?this.formatMoney(line):'Quotation required'}`; }); const total=this.cart.reduce((s,i)=>{ const p=this.getProduct(i.id); return s+(p?this.productAmount(p)*i.quantity:0); },0); const msg=`Hi HDS Consultancy, I would like to confirm these selected packages:

${lines.join('\n')}

Total estimate: ${this.formatMoney(total)}
Currency: ${this.currency}`; window.open(`https://wa.me/${this.data.business.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank','noopener'); }
}
new CartPage('cart-app').init();
